version: 2

project_name: tf

force_token: github

before:
  hooks:
    - go mod download

builds:
  - binary: tf
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - linux
      - windows
    flags:
      - -trimpath

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary

checksum:
  name_template: checksums.txt

changelog:
  use: github

brews:
  - name: tf
    description: Less verbose and more shell friendly Terraform
    homepage: https://github.com/dex4er/tf
    license: MIT
    repository:
      owner: dex4er
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"

snapcrafts:
  - name: tf-wrapper
    publish: true
    summary: Less verbose and more shell-friendly Terraform
    description: The original Terraform is abusively oververbosed. The tf wrapper makes Terraform more CLI-friendly.
    grade: devel
    confinement: classic
    license: MIT
    base: bare
    apps:
      tf-wrapper:
        aliases:
          - tf
        command: bin/tf
