name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Fake terraform
        run: |
          echo '#!/bin/bash' | sudo tee /usr/local/bin/terraform
          echo 'echo Fake Terraform' | sudo tee -a /usr/local/bin/terraform
          sudo chmod +x /usr/local/bin/terraform
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: ./tf.sh version
