name: Lint

on:
  - pull_request
  - push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.0.0
        with:
          check-mode: all
