name: OSV-Scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 34 10 * * 1
  workflow_dispatch: {}

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan-scheduled:
    name: OSV scan scheduled

    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@e92b5d07338d4f0ba0981dffed17c48976ca4730 # v2.2.3
    with:
      scan-args: |-
        -r
        --skip-git
        ./

  scan-pr:
    name: OSV scan PR

    if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable-pr.yml@e92b5d07338d4f0ba0981dffed17c48976ca4730 # v2.2.3
    with:
      scan-args: |-
        -r
        --skip-git
        ./
