name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    name: Release

    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Git tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4 # datasource=golang-version depName=go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 2.5.1 # datasource=github-releases depName=goreleaser/goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
