name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    name: Release

    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Git tags
        run: git fetch --force --tags

      - uses: jdx/mise-action@v2

      - name: Test binary
        run: |
          goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
