name: Snapshot

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - .editorconfig
      - .gitignore
      - .markdownlint.yaml
      - .trunk/**
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Build

    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Git tags
        run: git fetch --force --tags

      - name: Fake terraform
        run: |
          echo '#!/bin/bash' | sudo tee /usr/local/bin/terraform
          echo 'echo Fake Terraform' | sudo tee -a /usr/local/bin/terraform
          sudo chmod +x /usr/local/bin/terraform

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.3 # datasource=github-releases depName=golang/go

      - name: Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: 1.24.0 # datasource=github-releases depName=goreleaser/goreleaser
          args: build --clean --snapshot --single-target --output tf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test binary
        run: |
          ./tf version
