name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    name: Test

    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Fetch Git tags
        run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.4 # datasource=github-releases depName=hashicorp/terraform
          terraform_wrapper: false

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.9.0 # datasource=github-releases depName=opentofu/opentofu
          tofu_wrapper: false

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 2.6.1 # datasource=github-releases depName=goreleaser/goreleaser
          args: build --clean --snapshot --single-target --output tf

      - name: Run tests
        run: make test
