name: Trunk Check

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  trunk:
    name: Trunk Check

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
