name: Trunk Check

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  trunk:
    name: Trunk Check

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          check-mode: all
